### ISSUE TITLE
Starting download for /t/t/t/t_0.spd, file not found

### ISSUE THREAD

**Issue by kerckasha** [headswe/Swifty#144]
Recently swapped over to the new version and when attempting to update the repository I get this error, no such file exists in any of the addons or on the webserver.

Upon inspecting it further the issue seems to be due to abramia.pbo as upon deleting the existing file in my addon folder and having swifty just download the pbo whole sale the error disappeared

Another issue, updating to the latest version of CBA lead to this error:
2016-05-31 17:31:58,666 [13] INFO SwiftUpdater.Pages.Download - Packing cba_jr_disable_long_scopes_on_short_mg_rail.pbo
2016-05-31 17:31:58,666 [13] INFO SwiftUpdater.Pages.Download - E:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\optionals\cba_jr_disable_long_scopes_on_short_mg_rail\$PBOPREFIX$.backup exists..
2016-05-31 17:31:58,666 [13] INFO SwiftUpdater.Pages.Download - E:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\optionals\cba_jr_disable_long_scopes_on_short_mg_rail\config.bin exists..
2016-05-31 17:31:58,666 [13] INFO SwiftUpdater.Pages.Download - E:\SteamLibrary\SteamApps\common\Arma 3\@CBA_A3\optionals\cba_jr_disable_long_scopes_on_short_mg_rail\script_component.hpp exists..
2016-05-31 17:32:32,419 [13] INFO SwiftUpdater.Pages.Download - Crash
System.Exception: Pbo data not matching.
   at SwiftUpdater.Pages.Download.PackPbos(IEnumerable`1 changedPbos) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Pages\Download.cs:line 270
   at SwiftUpdater.Pages.Download.Worker_DoWork(Object sender, DoWorkEventArgs e) in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Pages\Download.cs:line 385
2016-05-31 17:32:32,437 [13] INFO SwiftUpdater.Pages.RepoView - Updateing view

**Comment by headswe** [comment]
This is caused by the obfuscation the author have decided to use.

**Comment by kerckasha** [comment]
You're kidding. So much for being a community if we're resorting to that kind of thing

**Comment by headswe** [comment]
CBA is not the culpit, sorry about that.

Do you have the Isla Abramia mod perhaps?

**Comment by kerckasha** [comment]
Yeah I meant Isla Abramia. I figure CBA's error is something else

**Comment by evromalarkey** [comment]
so what does this mean exactly? Because when I delete the t_0.spd, I can pack it without problems again, is the download then corrupted for client?

**Comment by evromalarkey** [comment]
I don't think it's Isla Abramia, I got the same problem but don't have Isla Abramia in repo.
I've got the error here - 
`2016-06-05 11:08:31,172 [10] INFO SwiftUpdater.Pages.Download - Finished download for @3cb_baf_vehicles/addons/uk3cb_baf_vehicles_wildcat/data/hhxnxrw.C_0.spd
2016-06-05 11:08:31,172 [9] INFO SwiftUpdater.Pages.Download - Finished download for @3cb_baf_vehicles/addons/uk3cb_baf_vehicles_wildcat/data/tfnsr.C_0.spd
2016-06-05 11:08:31,173 [6] INFO SwiftUpdater.Pages.Download - Starting download for /t/t/t/t_0.spd
2016-06-05 11:08:31,175 [17] INFO SwiftUpdater.Pages.Download - Finished download for @3cb_baf_vehicles/addons/uk3cb_baf_vehicles_wildcat/data/nunu.C_0.spd
2016-06-05 11:08:31,175 [6] INFO SwiftUpdater.Pages.Download - Starting download for addons/uk3cb_baf_vehicles_wildcat/aw159_wildcat_cannon_6.p3d_0.spd
2016-06-05 11:08:31,179 [11] INFO SwiftUpdater.Pages.Download - Finished download for @3cb_baf_vehicles/addons/uk3cb_baf_vehicles_wildcat/data/evkdvm.C_0.spd`

**Comment by headswe** [comment]
Yes because 3cb also use the pointless obsfucation

-----Original Message-----

**Comment by evromalarkey** [comment]
shame.. well after some testing, it's working alright now, although the patchcreator creates the /t/t/t/t_0.spd, it's alright for the client which gets correct data.. weird though

**Comment by headswe** [comment]
Fixed in 2.1.3.1

**Comment by evromalarkey** [comment]
the problem still persist, now it's doing also for diyala_province (also uses obfuscation, there werent problems before). Also other 3cb mods also use obfuscation, but the error only happens with 3cb vehicles

**Comment by headswe** [comment]
@evromalarkey Are you using the new swifty-cli?

**Comment by evromalarkey** [comment]
yes, this is the command I'm using via bat 
`start %LOCALAPPDATA%\Swifty\app-2.1.3.1\tools\swifty-cli.exe create %~dp0mods %~dp0smods`
